name: Build sillyGirl K3 ipq806x
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v5

      - name: 使用Go1.20（关键！规避Cortex‑A9硬件div问题）
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.14'

      - name: 交叉编译
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: arm
          GOARM: 7
        run: |
          go build -ldflags "-w -s" -o sillygirl-k3 .

      - name: Release发布
        uses: softprops/action-gh-release@v2
        with:
          tag_name: k3-build
          name: sillyGirl‑ipq806x‑K3
          files: sillygirl-k3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
